name: Test Multiply Base

on:
  push:
    branches:
      - test-github-action

jobs:
  test-action-works:
    runs-on: ubuntu-latest
    name: test no config file
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test multiply base
        uses: ./
        with:
          files: './examples/no-config-file ./examples/only-warning'
          failOnWarnings: true