name: Test Use Config File

on:
  push:
    branches:
      - test-github-action
jobs:
  test-action-works:
    runs-on: ubuntu-latest
    name: test use config file
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test use config file
        uses: ./
        with:
          files: './examples/use-config-file'
          failOnWarnings: true
          configFile: './examples/use-config-file/.lintmdrc'